#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Using: $0 <filename> <newext>"
	exit 1
fi

filename=$1
newext=$2

base_name=$(basename "$filename" .${filename##*.})

new_filename="${base_name}.${newext}"

mv "$filename" "$new_filename"

echo "File renamed to $new_filename"
