#!/bin/bash

if [ -z "$1" ]; then
	echo "Please, provide file"
	exit 1
fi

dates=$(awk '{print $1}' "$1" | sort | uniq)

for date in $dates; do
	count=$(awk -v date="$date" '{if ($1 == date && $3 == "OK") print $0}' "$1" | wc -l)
	echo "$date $count"
done
