#!/bin/bash

outfile="output.txt"
if [ -f "$outfile" ]; then
	outfile="output_new.txt"
fi

echo "Current processes:" > "$outfile"
ps aux >> "$outfile"

echo -e "\nOpen ports:" >> "$outfile"
netstat -tuln >> "$outfile" 

echo -e "\nSystem users:" >> "$outfile"
who >> "$outfile"

echo -e "\nLocal IP:" >> "$outfile"
hostname -I >> "$outfile"

echo -e "\nFree space on disk:" >> "$outfile"
df -h >> "$outfile"

echo "Info written to file $outfile"
