Vagrant.configure("2") do |config|
  # Используем образ Debian 12
  config.vm.box = "generic/debian12"

  # Настройка hostname
  config.vm.hostname = "OS-security"
  
  # Настройки VMware
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "4096"
    vmware.vmx["numvcpus"] = "4"
    vmware.vmx["ethernet0.natdnshostresolver1"] = "true"
    vmware.vmx["ethernet0.natdnsproxy1"] = "true"
  end  # Закрываем блок provider

  # Проброс SSH-ключа
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /home/vagrant/.ssh
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCp7eiRguHxbdpYwnGkHoC78QFQMDVfitoJhvpbQgvcU7PWAd3eb0yVULZH9+LDBPZDQLX7E1dus3aJWdR0/jB62uBgtD90oEbdVcoRBydYbY9GVEnnfN9fimPU9vyHyt6MR2Hgpr+1BCKK8AOiXobYB/b2mVdGaeHVt7KcrV+hH7X8hvsjm/LEYxY3ZQGp+/wbKMHXib8XmJNlENIcthvL4xJU2gAC2ydyCa3U86S5zFv/02FmbfquopK3zPwK2uJuv6JKVoCE7MvlEkLtuOOIk6fFcxDIP8xvezD9Qd2XAjkQDIt6sxtWHOwsxdbIsp1CBtIAKdbvoA8vB2O5WkFMNp37oB0dNRcx3PgL/cJJJSYX1TW1mL5VMP7hkxkhNm5JHptbMx49xl0F8uKSS0CTQKUbBM7c0KH3X3laJvC3v3b2cT9bB4762BHC1WsxkS+IvAG6wt8j6xpXKQnHRxRtlcdhVXMsXlL1br94RIJqCllAbgxJz/zpmkF8xprlgQk= gkhly@DESKTOP-3INKQHN" >> /home/vagrant/.ssh/authorized_keys
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # Установка переменной окружения для предотвращения интерактивных запросов
    export DEBIAN_FRONTEND=noninteractive

    # Обновляем систему и устанавливаем необходимые пакеты
    sudo apt-get update
    sudo apt-get upgrade -y --fix-missing
    sudo apt-get install -y nginx sudo

# Создаем пользователей user1, user2 и user3
    sudo useradd -m user1
    sudo useradd -m user2
    sudo useradd -m user3

    # Устанавливаем пароли для пользователей
    echo "user1:password" | sudo chpasswd
    echo "user2:password" | sudo chpasswd
    echo "user3:password" | sudo chpasswd

    # Добавляем user2 в группу sudo
    sudo usermod -aG sudo user2

    # Создаем группу gigachads и добавляем пользователей в нее
    sudo groupadd gigachad
    sudo usermod -aG gigachads user1
    sudo usermod -aG gigachads user2
    sudo usermod -aG gigachads user3

    # Настройка sudoers для разрешения прав
    echo "user2    ALL=(ALL) ALL" | sudo tee -a /etc/sudoers > /dev/null
    echo "user1    ALL=(user2) /bin/ls" | sudo tee -a /etc/sudoers > /dev/null
    echo "%gigachads    ALL=(ALL) NOPASSWD: /usr/bin/apt-get update, /usr/bin/apt-get upgrade, /sbin/shutdown" | sudo tee -a /etc/sudoers > /dev/null

    # Проверяем права доступа
    sudo chmod 755 /home/user1 /home/user2 /home/user3
SHELL
end
