Vagrant.configure("2") do |config|
  # Используем образ Debian 12
  config.vm.box = "generic/debian12"

  # Настройка hostname
  config.vm.hostname = "OS-security"
  
  # Настройки VMware
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "4096"
    vmware.vmx["numvcpus"] = "4"
    vmware.vmx["ethernet0.natdnshostresolver1"] = "true"
    vmware.vmx["ethernet0.natdnsproxy1"] = "true"
  end  # Закрываем блок provider

  # Проброс SSH-ключа
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /home/vagrant/.ssh
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCp7eiRguHxbdpYwnGkHoC78QFQMDVfitoJhvpbQgvcU7PWAd3eb0yVULZH9+LDBPZDQLX7E1dus3aJWdR0/jB62uBgtD90oEbdVcoRBydYbY9GVEnnfN9fimPU9vyHyt6MR2Hgpr+1BCKK8AOiXobYB/b2mVdGaeHVt7KcrV+hH7X8hvsjm/LEYxY3ZQGp+/wbKMHXib8XmJNlENIcthvL4xJU2gAC2ydyCa3U86S5zFv/02FmbfquopK3zPwK2uJuv6JKVoCE7MvlEkLtuOOIk6fFcxDIP8xvezD9Qd2XAjkQDIt6sxtWHOwsxdbIsp1CBtIAKdbvoA8vB2O5WkFMNp37oB0dNRcx3PgL/cJJJSYX1TW1mL5VMP7hkxkhNm5JHptbMx49xl0F8uKSS0CTQKUbBM7c0KH3X3laJvC3v3b2cT9bB4762BHC1WsxkS+IvAG6wt8j6xpXKQnHRxRtlcdhVXMsXlL1br94RIJqCllAbgxJz/zpmkF8xprlgQk= gkhly@DESKTOP-3INKQHN" >> /home/vagrant/.ssh/authorized_keys
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # Установка переменной окружения для предотвращения интерактивных запросов
    export DEBIAN_FRONTEND=noninteractive

    echo "postfix postfix/mailname string OS-security" | debconf-set-selections
	echo "postfix postfix/main_mailer_type string 'OS-security'" | debconf-set-selections
	
	# Прописываем конфигурацию для iptables-persistent, чтобы избежать остановки на интерактивных оболочках
	echo "iptables-persistent iptables-persistent/autosave_v4 boolean true" | debconf-set-selections
	echo "iptables-persistent iptables-persistent/autosave_v6 boolean true" | debconf-set-selections

	# Обновляем систему и устанавливаем необходимые пакеты
    sudo apt-get update
    sudo apt-get upgrade -y --fix-missing
    sudo apt-get install -y acl iptables-persistent nginx debootstrap policykit-1 postfix network-manager packagekit
	
	# Задание 1
	
	# Создаем группы
	sudo groupadd it
	sudo groupadd sales
	sudo groupadd company
	
	# Создаем директории
	sudo mkdir -p /company/it /company/sales /company/shared
	
	# Создаем пользователей
	sudo useradd -m -s /bin/bash -g company -G it ituser1
	sudo useradd -m -s /bin/bash -g company -G it ituser2
	sudo useradd -m -s /bin/bash -g company -G it itadmin
	
	sudo useradd -m -s /sin/sh -g company -G sales suser1
	sudo useradd -m -s /sin/sh -g company -G sales suser2
	sudo useradd -m -s /sin/sh -g company -G sales sadmin
	
	# Настраиваем права доступа
	sudo chmod 770 /company/it
	sudo chown root:it /company/it
	
	sudo chmod 770 /company/sales
	sudo chown root:sales /company/sales
	
	# Все пользователи могут видеть /company/shared
	sudo chmod 755 /company/shared
	
	# Создание файлов в shared
    sudo touch /company/shared/ituser1
    sudo touch /company/shared/ituser2
    sudo touch /company/shared/itadmin
    sudo touch /company/shared/suser1
    sudo touch /company/shared/suser2
    sudo touch /company/shared/sadmin
	
	# Задание 2
	
	# Создаем группы
	sudo groupadd academy
	sudo groupadd teachers
	sudo groupadd students
	sudo groupadd staff
	
	# Создаем директории
	sudo mkdir -p /academy/students /academy/teachers /academy/staff
	sudo mkdir -p /academy/secret
	
	# Создаем пользователей
	sudo useradd -m -s /bin/bash -g students student
	sudo useradd -m -s /bin/bash -g teachers teacher
	
	# Домашняя директория для студентов
	sudo mkdir /academy/students/student
	sudo chown student:students /academy/students/student
	
	# Домашняя директория для учителей
	sudo mkdir /academy/teachers/teacher
	sudo chown teacher:teachers /academy/teachers/teacher
	
	# Настройка прав доступа для студентов
    sudo chmod 750 /academy/students
    sudo chmod 750 /academy/teachers
    sudo chmod 750 /academy/staff
    sudo chmod 755 /academy/secret
	
	# Настройка доступа для группы staff
    sudo setfacl -m g:staff:rwx /academy/students
    sudo setfacl -m g:staff:rwx /academy/teachers

    # Разрешение на создание файлов в /academy/secret
    sudo setfacl -m g:teachers:rw /academy/secret
    sudo setfacl -m g:staff:rw /academy/secret

    # Файл top_secret в /academy/secret
    sudo touch /academy/secret/top_secret
    sudo chattr +i /academy/secret/top_secret

    # Разрешение на создание файлов
    sudo setfacl -m g:teachers:rw /academy/secret
    sudo setfacl -m g:staff:rw /academy/secret

    # Разрешение на удаление файлов от имени группы учителей
    sudo visudo -f /etc/sudoers.d/students_teachers << EOF
    %students ALL=(%teachers) NOPASSWD: /bin/rm /academy/secret/*
    EOF
	
	# Задание 3
	
	# Создаем директории
	sudo mkdir -p /home/company/homedirs /home/company/sales /home/company/marketing /home/company/shared
	
	# Создаем группы
	sudo groupadd company2
	sudo groupadd sales2
	sudo groupadd marketing2
	
	# Создаем пользователей
	sudo useradd -m -s /bin/bash -g sales2 -G company2 mike
	sudo useradd -m -s /bin/bash -g marketing2 -G company2 john
	
	# Настройка прав доступа
	
    # Директория /home/company/homedirs для пользователей
    sudo mkdir /home/company/homedirs/mike
    sudo mkdir /home/company/homedirs/john
    sudo chown mike:sales /home/company/homedirs/mike
    sudo chown john:marketing /home/company/homedirs/john

	# Директория /home/company/sales для группы sales
    sudo chown root:sales2 /home/company/sales
    sudo chmod 770 /home/company/sales

    # Директория /home/company/marketing для группы marketing
    sudo chown root:marketing2 /home/company/marketing
    sudo chmod 770 /home/company/marketing

    # Директория /home/company/shared для общей группы company
    sudo chown root:company2 /home/company/shared
    sudo chmod 2770 /home/company/shared
    sudo setfacl -m d:g:company2:rwx /home/company/shared
    sudo setfacl -m g:company2:rwx /home/company/shared
	
	# Задание 4
	
    # Создание директорий внутри /data
    sudo mkdir -p /data/marketing /data/sales /data/it

    # Создание групп
    sudo groupadd marketing3
    sudo groupadd sales3
    sudo groupadd it3

    # Создание пользователей
    sudo useradd -m -s /bin/bash -g marketing3 user.marketing
    sudo useradd -m -s /bin/bash -g sales3 user.sales
    sudo useradd -m -s /bin/bash admin
    sudo useradd -m -s /bin/bash backup

    # Настройка прав доступа для директорий
    sudo chown user.marketing:marketing3 /data/marketing
    sudo chown user.sales:sales3 /data/sales
    sudo chown admin:admin /data/it
    sudo chmod 700 /data/marketing /data/sales /data/it

    # Настройка прав для admin full
    sudo setfacl -m u:admin:rwx /data/marketing
    sudo setfacl -m u:admin:rwx /data/sales
    sudo setfacl -m u:admin:rwx /data/it

    # Настройка прав для backup read-only
    sudo setfacl -m u:backup:rx /data/marketing
    sudo setfacl -m u:backup:rx /data/sales
    sudo setfacl -m u:backup:rx /data/it
	
	# Задание 5
	
    # Создание директории /company2
    sudo mkdir /company2
    sudo chown root:company /company2
    sudo chmod 770 /company2

    # Настройка маски для группы, чтобы все создаваемые файлы имели группу company
    sudo chmod g+s /company2

    # Проверка прав доступа для /company
    ls -ld /company2
	
	# Задание 6 (ACL)
	
	# Создаем группу developers
	sudo groupadd developers
	
    # Создание файла testfile.txt в домашнем каталоге
    touch ~/testfile.txt

    # Установка ACL для пользователя john с правами на чтение
    sudo setfacl -m u:john:r-- ~/testfile.txt

    # Проверка ACL на файле
    getfacl ~/testfile.txt

    # Создание директории testdir
    mkdir ~/testdir

    # Установка ACL для директории testdir для группы developers
    sudo setfacl -m g:developers:rwx ~/testdir
    # Установка наследования прав
    sudo setfacl -d -m g:developers:rwx ~/testdir

    # Создание файла и директории внутри testdir для проверки наследования прав
    touch ~/testdir/testfile_inside
    mkdir ~/testdir/testdir_inside

    # Изменение прав для пользователя john на файле testfile.txt (право на запись)
    sudo setfacl -m u:john:rw ~/testfile.txt
    # Проверка изменений с помощью getfacl
    getfacl ~/testfile.txt

    # Удаление всех ACL с файла
    sudo setfacl -b ~/testfile.txt
    # Проверка после удаления ACL
    getfacl ~/testfile.txt

    # Пример с масками ACL
    sudo setfacl -m m::r-- ~/testdir
    sudo setfacl -m u:john:rwx ~/testdir/testfile_inside
    getfacl ~/testdir/testfile_inside
	
  SHELL
  end
